version: '3'

services:
  bnbdnode0:
    container_name: bnbdnode0
    image: "binance/bnbdnode"
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-bnbchaind.log}
    volumes:
      - ./build:/bnbchaind:Z
    networks:
      localnet:
        ipv4_address: 172.20.0.2

  bnbdnode1:
    container_name: bnbdnode1
    image: "binance/bnbdnode"
    ports:
      - "26659-26660:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-bnbchaind.log}
    volumes:
      - ./build:/bnbchaind:Z
    networks:
      localnet:
        ipv4_address: 172.20.0.3

  bnbdnode2:
    container_name: bnbdnode2
    image: "binance/bnbdnode"
    environment:
      - ID=2
      - LOG=${LOG:-bnbchaind.log}
    ports:
      - "26661-26662:26656-26657"
    volumes:
      - ./build:/bnbchaind:Z
    networks:
      localnet:
        ipv4_address: 172.20.0.4

  bnbdnode3:
    container_name: bnbdnode3
    image: "binance/bnbdnode"
    environment:
      - ID=3
      - LOG=${LOG:-bnbchaind.log}
    ports:
      - "26663-26664:26656-26657"
    volumes:
      - ./build:/bnbchaind:Z
    networks:
      localnet:
        ipv4_address: 172.20.0.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.20.0.0/16

