kind: Service
apiVersion: v1
metadata:
  labels:
    app: tendermint-seed
  name: seed
spec:
  ports:
  - port: 26656
    targetPort: 26656
    name: p2p
  - port: 26657
    targetPort: 26657
    name: rpc
  - port: 80
    targetPort: 8080
    name: server
  selector:
    app: tendermint-seed
  type: LoadBalancer
