kind: Service
apiVersion: v1
metadata:
  labels:
    tendermint-identity: validator-{{INSTANCE}}
  name: validator-{{INSTANCE}}
spec:
  clusterIP: None
  ports:
  - name: api-server
    port: 8080
    targetPort: 8080
  - name: p2p
    port: 26656
    targetPort: 26656
  - name: prome
    port: 26660
    targetPort: 26660
  - name: rpc
    port: 26657
    targetPort: 26657
  type: ClusterIP
