kind: Service
apiVersion: v1
metadata:
  labels:
    tendermint-identity: witness-explorer
  name: witness-explorer
spec:
  ports:
  - name: api-server
    port: 8080
    targetPort: 8080
  - name: p2p
    port: 26656
    targetPort: 26656
  - name: rpc
    port: 26657
    targetPort: 26657
  selector:
    tendermint-identity: witness-explorer
  type: ClusterIP
