apiVersion: apps/v1
kind: Deployment
metadata:
  name: witness-order
  labels:
    tendermint-identity: witness-order
    app: tendermint-witness-order
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      tendermint-identity: witness-order
      app: tendermint-witness-order
  template:
    metadata:
      labels:
        tendermint-identity: witness-order
        app: tendermint-witness-order
    spec:
      ## Use nodeSelector to hold same data volumes in host machine and to avoid host port conflict.
      nodeSelector:
        tendermint-witness-order: witness-order
#      affinity:
#        podAntiAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#          - labelSelector:
#              matchExpressions:
#              - key: app
#                operator: In
#                values:
#                - tendermint-witness-order
#            topologyKey: "kubernetes.io/hostname"
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      terminationGracePeriodSeconds: 0
      containers:
      - name: bnbchaind
        image: {{DOCKER_REGISTRY}}/kube-bnbchain
        imagePullPolicy: Always
        env:
        - name: DEPLOY_MODE
          value: "{{DEPLOY_MODE}}"
        - name: REBUILD
          value: "{{REBUILD}}"
        command:
        - /bin/sh
        - -c
        - if [ "$REBUILD"x == "TRUE"x ]; then rm -rf /bnbchaind/gaiad/*; fi; mkdir -p /bnbchaind/gaiad/config; cp /bnbchaind/config/* /bnbchaind/gaiad/config/;/bnbchaind/bnbchaind start --home "/bnbchaind/gaiad" --p2p.laddr  "tcp://0.0.0.0:26656" --address "tcp://0.0.0.0:26658" --rpc.laddr "tcp://0.0.0.0:26657"> /bnbchaind/gaiad/node.log 2>&1
        volumeMounts:
        - mountPath: /bnbchaind/gaiad
          name: gaiad-volume
        - name: config-volume
          mountPath: /bnbchaind/config
      - name: api-server
        image: {{DOCKER_REGISTRY}}/kube-bnbchain
        imagePullPolicy: Always
        env:
        - name: DEPLOY_MODE
          value: "{{DEPLOY_MODE}}"
        command:
        - /bin/sh
        - -c
        - /bnbchaind/bnbcli --laddr tcp://0.0.0.0:8080 --node tcp://localhost:26657 api-server > /bnbchaind/gaiad/api-server.log 2>&1
        volumeMounts:
        - mountPath: /bnbchaind/gaiad
          name: gaiad-volume
      volumes:
      - name: gaiad-volume
        hostPath:
          path: /opt/bnbchaind/witness-order
      - name: config-volume
        configMap:
          name: witness-order-config