apiVersion: apps/v1
kind: Deployment
metadata:
  name: witness-explorer
  labels:
    tendermint-identity: witness-explorer
    app: tendermint-witness-explorer
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      tendermint-identity: witness-explorer
      app: tendermint-witness-explorer
  template:
    metadata:
      labels:
        tendermint-identity: witness-explorer
        app: tendermint-witness-explorer
    spec:
      ## Use nodeSelector to hold same data volumes in host machine and to avoid host port conflict.
      nodeSelector:
        tendermint-witness-explorer: witness-explorer
#      affinity:
#        podAntiAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#          - labelSelector:
#              matchExpressions:
#              - key: app
#                operator: In
#                values:
#                - tendermint-witness-explorer
#            topologyKey: "kubernetes.io/hostname"
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      terminationGracePeriodSeconds: 0
      containers:
      - name: bnbchaind
        image: {{DOCKER_REGISTRY}}/kube-bnbchain:{{IMAGE_TAG}}
        imagePullPolicy: Always
        env:
        - name: DEPLOY_MODE
          value: "{{DEPLOY_MODE}}"
        - name: REBUILD
          value: "{{REBUILD}}"
        command:
        - /bin/sh
        - -c
        - if [ "$REBUILD"x == "TRUE"x ]; then rm -rf /bnbchaind/bnbchain/*; fi;mkdir -p /bnbchaind/bnbchain/config; cp /bnbchaind/config/* /bnbchaind/bnbchain/config/;/bnbchaind/bnbchaind start --home "/bnbchaind/bnbchain" --p2p.laddr  "tcp://0.0.0.0:26656" --address "tcp://0.0.0.0:26658" --rpc.laddr "tcp://0.0.0.0:26657">> /bnbchaind/bnbchain/node.log 2>&1
        volumeMounts:
        - mountPath: /bnbchaind/bnbchain
          name: bnbchain-volume
        - name: config-volume
          mountPath: /bnbchaind/config
      - name: api-server
        image: {{DOCKER_REGISTRY}}/kube-bnbchain:{{IMAGE_TAG}}
        imagePullPolicy: Always
        env:
        - name: DEPLOY_MODE
          value: "{{DEPLOY_MODE}}"
        command:
        - /bin/sh
        - -c
        - /bnbchaind/bnbcli --chain-id chain-bnb  --home /bnbchaind/cli_home  --laddr tcp://0.0.0.0:8080 --node tcp://localhost:26657 api-server >> /bnbchaind/bnbchain/api-server.log 2>&1
        volumeMounts:
        - mountPath: /bnbchaind/bnbchain
          name: bnbchain-volume
        - name: cli-volume
          mountPath: /bnbchaind/cli_home/keys/keys.db/
      volumes:
      - name: bnbchain-volume
        hostPath:
          path: /server/bnbchaind/witness-explorer
      - name: config-volume
        configMap:
          name: witness-explorer-config
      - name: cli-volume
        configMap:
          name: cli-config