#!/usr/bin/expect

set symbol [lindex $argv 0]
set id [lindex $argv 1]
set from [lindex $argv 2]
set chain_id [lindex $argv 3]
set home [lindex $argv 4]

set timeout 30
	if {"$home" == ""} {
		spawn ./bnbcli dex cancel -l $symbol -i $id --from $from --chain-id=$chain_id -f $id
	} else {
		spawn ./bnbcli dex cancel -l $symbol --home $home -i $id --from $from --chain-id=$chain_id -f $id
	}
	expect "Password*"
	send "12345678\r"
interact
