#!/usr/bin/expect

set swapID [lindex $argv 0]
set amount [lindex $argv 1]
set from [lindex $argv 2]
set chain_id [lindex $argv 3]
set home [lindex $argv 4]

set timeout 30
	if {"${home}" == ""} {
		spawn ./bnbcli token deposit --from $from --chain-id $chain_id --amount $amount --swap-id $swapID
	} else {
		spawn ./bnbcli token deposit --home $home --from $from --chain-id $chain_id --amount $amount --swap-id $swapID
	}
	expect "Password*"
	send "12345678\r"
interact
