#!/usr/bin/expect

set symbol [lindex $argv 0]
set amount [lindex $argv 1]
set from [lindex $argv 2]
set chain_id [lindex $argv 3]
set home [lindex $argv 4]

set timeout 30
	if {"${home}" == ""} {
		spawn ./bnbcli token mint -y -s $symbol  -n $amount --from $from --chain-id $chain_id
	} else {
		spawn ./bnbcli token mint -y --home $home -s $symbol -n $amount --from $from --chain-id $chain_id
	}
	expect "Password*"
	send "12345678\r"
interact
