#!/usr/bin/expect

set secret [lindex $argv 0]
set name [lindex $argv 1]
set recover [lindex $argv 2]
set home [lindex $argv 3]

if { "${recover}" == "true" } {
	set recover "--recover"
} else {
	set recover ""
}

set timeout 30
	spawn ./bnbcli keys add --home ./${home} $recover $name
	expect "Enter*"
	send "12345678\r"
	expect "Repeat*"
	send "12345678\r"
	expect "Enter*"
	send "${secret}\r"
interact
