#!/usr/bin/expect

set home [lindex $argv 0]
set from [lindex $argv 1]
set chain_id [lindex $argv 2]
set amount [lindex $argv 3]
set validator_addr_src [lindex $argv 4]
set validator_addr_dst [lindex $argv 5]

set timeout 30
    spawn ./bnbcli staking redelegate --home $home --from $from --chain-id=$chain_id --amount $amount --addr-validator-source $validator_addr_src --addr-validator-dest $validator_addr_dst
	expect "Password*"
	send "12345678\r"
expect eof
