#!/usr/bin/expect

set swapID [lindex $argv 0]
set from [lindex $argv 1]
set chain_id [lindex $argv 2]
set home [lindex $argv 3]

set timeout 30
	if {"${home}" == ""} {
		spawn ./bnbcli token refund --from $from --chain-id $chain_id --swap-id $swapID
	} else {
		spawn ./bnbcli token refund --home $home --from $from --chain-id $chain_id --swap-id $swapID
	}
	expect "Password*"
	send "12345678\r"
interact
