#!/usr/bin/expect

set flags [lindex $argv 0]
set from [lindex $argv 1]
set chain_id [lindex $argv 2]
set home [lindex $argv 3]

set timeout 30
	if {"${home}" == ""} {
		spawn ./bnbcli account_flags set-account-flags -y --account-flags $flags --from $from --chain-id $chain_id
	} else {
		spawn ./bnbcli account_flags set-account-flags -y --home $home --account-flags $flags --from $from --chain-id $chain_id
	}
	expect "Password*"
	send "12345678\r"
interact
